const fs = require('fs');
let code = fs.readFileSync('d:\\jp\\src\\App.jsx', 'utf8');

const regex = /接在前面：<span className="bg-slate-100 text-slate-700 px-2 py-0\.5 rounded-md font-medium border border-slate-200">\{verbForms\.find\(f=>f\.id===g\.baseForm\)\?\.label\}<\/span>(\r?\n)\s*\{g\.removeStr && <span className="text-red-400 font-bold">-「\{g\.removeStr\}」<\/span>\}(\r?\n)\s*<span className="text-emerald-500 font-bold">\+「\{g\.appendStr\}」<\/span>/g;

const replacement = `接在前面：<span className="bg-slate-100 text-slate-700 px-2 py-0.5 rounded-md font-medium border border-slate-200">{verbForms.find(f=>f.id===g.baseForm)?.label}</span>$1                               <span className="ml-1 text-slate-600 font-bold flex items-center flex-wrap gap-1 bg-slate-50 px-2.5 py-1 rounded-lg border border-slate-100 shadow-sm">$2                                  {(() => {$2                                      const mockVerbs = { masu: '食べます', te: '食べて', ta: '食べた', nai: '食べない', nakatta: '食べなかった', ba: '食べれば', volitional: '食べよう', jisho: '食べる', potential: '食べられる', passive: '食べられる', causative: '食べさせる', causative_passive: '食べさせられる' };$2                                      const baseWord = mockVerbs[g.baseForm] || '〇〇';$2                                      let displayStr = baseWord;$2                                      let resultStr = baseWord;$2                                      if (g.removeStr) {$2                                          if (baseWord.endsWith(g.removeStr)) {$2                                              displayStr = baseWord.slice(0, -g.removeStr.length) + \`~~\${g.removeStr}~~\`;$2                                              resultStr = baseWord.slice(0, -g.removeStr.length);$2                                          } else {$2                                              displayStr = baseWord + \`~~\${g.removeStr}~~\`;$2                                          }$2                                      }$2                                      resultStr += (g.appendStr || '');$2                                      return ($2                                        <>$2                                          <span className="text-slate-400 text-[13px] font-normal mr-0.5">例如</span>$2                                          <span>{renderTextWithStrikethrough(displayStr)}</span>$2                                          {g.appendStr && ($2                                            <>$2                                              <span className="text-emerald-500 font-black px-0.5">+</span>$2                                              <span className="text-emerald-600 font-bold">{g.appendStr}</span>$2                                            </>$2                                          )}$2                                          <ArrowRight className="w-3.5 h-3.5 text-slate-400 mx-0.5" />$2                                          <span className="text-indigo-600 font-bold">{resultStr}</span>$2                                        </>$2                                      );$2                                  })()}$2                               </span>`;

if(regex.test(code)) {
    code = code.replace(regex, replacement);
    fs.writeFileSync('d:\\jp\\src\\App.jsx', code, 'utf8');
    console.log("Success");
} else {
    console.log("Failed to find pattern");
}
